language: node_js
node_js: 10.13.0
install:
    - wget https://github.com/gohugoio/hugo/releases/download/v0.53/hugo_0.53_Linux-64bit.deb
    - sudo dpkg -i hugo*.deb
    - hugo version
    - rm -rf public
    - npm install
    
script:
    - hugo --buildFuture
    - gulp
    - echo 'Build done!'

after_success:
    - pwd
    - cd static/data
    - ls
    - java -Dfile.encoding=utf-8 -jar sb.jar
    - ls
    - cp * /home/travis/build/ziyan1215/helloword/public/data/
    - cd    /home/travis/build/ziyan1215/helloword 
    - ls 
    - git config --global user.email "xuziyanmiss@gmail.com"
    - git config --global user.name "ziyan1215"
    - git clone https://${ACCESS_TOKEN}@github.com/ziyan1215/xuziyan.ga.git container
    - rm -rf container/*
    - cp -r public/* container 
    - cd container
    - git add .
    - git commit -m 'Travis upate blog'
    - git push -u origin gh-pages -f
    - curl -d " " ${DEPLOY_API}






