language: python

python:
    - "3.6"

install:
    - uname -a
    - wget https://github.com/gohugoio/hugo/releases/download/v0.53/hugo_0.53_Linux-64bit.deb
    - sudo dpkg -i hugo*.deb
    - hugo version
    - rm -rf blog
    - ls
    - pwd


script:
    - hugo -d blog --buildFuture
    - echo 'Hugo build done!'
after_success:
    - git config --global user.email "xuziyanmiss@gmail.com"
    - git config --global user.name "ziyan1215"
    - git clone https://${ACCESS_TOKEN}@github.com/ziyan1215/xuziyan.ga.git container
    - rm -rf container/*
    - cp -r blog/* container 
    - cd container
    - ls
    - git add .
    - git commit -m 'Travis upate blog'
    - git push -u origin gh-pages -f
    - curl -d "" ${DEPLOY_API}
